### ISSUE TITLE
Nice app, but trouble with floating windows.

### ISSUE THREAD

**Issue by wittend** [ZebusJesus/Meshtastic-PyGUI#13]
Can't read display.  

On startup (Ubuntu Linux 18.10) all windows pile up at with the center of the cluster at the point where my two monitors meet. It does not seem to be possible to move them. 

Plus I personally don't like unconstrained multi window apps.

Replicate: use computer connected to more than one monitor.  Run program.  watch it screw up.

Dave

**Comment by wittend** [comment]
Solved.  My ignorance.  I haven't encountered this kind of interface in a very long time.

**Comment by ZebusJesus** [comment]
Yeah there have been some updates to PySimpleGUI that make it behave strangely it seems, Im working on fixing those bugs.
