### ISSUE TITLE
runpi 

### ISSUE THREAD

**Issue by ZebusJesus** [ZebusJesus/Meshtastic-PyGUI#9]
**Describe the bug**
unble to luaunch app without using python -m 

**To Reproduce**
```
meshtastic_pygui
```

**Expected behavior**
Launch application 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows, Linuc, OSX

**Additional context**

**Comment by danmandle** [comment]
Not a bug. Documentation in README has the following:
```
Launch Command

Windows:

python -m meshtastic_pygui

MacOS:

python3 -m meshtastic_pygui
```
